# Generated by Django 4.2.5 on 2023-10-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='other',
            field=models.ImageField(default='', upload_to='post'),
        ),
    ]
